AllCops:
  DisabledByDefault: true
  
Layout/AccessModifierIndentation:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true
  
Lint/UnusedMethodArgument:
  Enabled: true
