AllCops:
  DisabledByDefault: true
  
Layout/AccessModifierIndentation:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/AlignArray:
  Enabled: true

Performance/RedundantSortBy:
  Enabled: true
  
Lint/UnusedMethodArgument:
  Enabled: true
